# Generated by Django 5.2.6 on 2025-09-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
