# Generated by Django 5.2.6 on 2025-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_visa_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
