# Generated by Django 5.2.6 on 2025-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_visa_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='user_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
