# Generated by Django 5.2.6 on 2025-09-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_visa_user_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='read',
            new_name='is_read',
        ),
    ]
